//user auth links
POST http://localhost:3001/register
Content-Type: application/json

{
    "name":"asdf",
    "age":20,
    "email":"tushar123asdfail.com",
    "password":"tushdfar1234",
    "Role":"Investor"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "email":"tushar1234@gmail.com",
    "password":"tushar1234"
}

###

//pitch routes
POST http://localhost:3001/pitch/add
Content-Type: application/json

{
    "company_name":"Dummy Name",
    "pitcher_name":"Dummy name",
    "educational_background":"Dummy",
    "money":100000,
    "equity":20,
    "description":"Dummy description"
}




















